name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    environment: Actions
    env: 
      BASE_URL: ${{ vars.TEST }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '25'
        cache: 'npm'
        cache-dependency-path: |
          pw-practice-app/package-lock.json
          playwright/package-lock.json
    
    # Install app deps
    - name: Install app dependencies
      id: playwright-version
      run: |
        cd pw-practice-app
        npm ci

    # Start app in background
    - name: Start app
      run: |
        cd pw-practice-app
        npm start &
    
    # Wait for the app
    - name: Wait for app
      run: npx wait-on ${{ env.BASE_URL }}
    
    # Install the browsers
    - name: Install Playwright Browsers
      run: |
        cd playwright
        npx playwright install --with-deps chromium
    
    # Run the test
    - name: Run Playwright tests
      run: |
        cd playwright
        npx playwright test --project=chromium

    # Upload report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
